# Generated by Django 3.2.16 on 2023-01-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='catalog.offer', verbose_name='offer'),
        ),
        migrations.AlterField(
            model_name='music',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='catalog.offer', verbose_name='offer'),
        ),
        migrations.AlterField(
            model_name='musictext',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='catalog.offer', verbose_name='offer'),
        ),
    ]
