# Generated by Django 3.2.16 on 2023-01-30 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='наименование')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, verbose_name='значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.offer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prod', to='catalog.property')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='property',
            field=models.ManyToManyField(through='catalog.ProductProperty', to='catalog.Property', verbose_name='характеристики'),
        ),
    ]
